name: Build Android Kernel

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 镜像

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 检出当前仓库

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev bc git

    - name: Clone kernel source
      run: |
        git clone --depth=1 --branch oneplus/sm8650_v_15.0.0_oneplus_ace5 https://github.com/OnePlusOSS/android_kernel_oneplus_sm8650.git kernel
        git clone --depth=1 --branch oneplus/sm8650_v_15.0.0_oneplus_ace5 https://github.com/OnePlusOSS/android_kernel_common_oneplus_sm8650.git kernel/common
        git clone --depth=1 --branch oneplus/sm8650_v_15.0.0_oneplus_ace5 https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8650.git kernel/modules

    - name: Set up build environment
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export PATH=$PATH:/usr/bin

    - name: Build kernel
      run: |
        cd kernel
        make oneplus/sm8650_v_15.0.0_oneplus_ace5_defconfig
        make -j$(nproc)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: kernel/arch/arm64/boot/Image.gz-dtb
